### ISSUE TITLE
FPS Counter

### ISSUE THREAD

**Issue by Lewiscowles1986** [mpwelton/FlowFieldAnimated#1]
I experimented with this and made the following edit to the end of the `draw()` call to get an FPS counter, so we can verify results of our experiments

```
  // Save current style settings
  pushStyle();

  // Display FPS
  fill(0); // Ensure the text is visible
  textSize(24);
  text("FPS: " + nf(frameRate, 1, 2), 10, height - 10);

  // Restore previous style settings
  popStyle();
```

Not as good as a profiler for code improvements, but it has helped

**Comment by Lewiscowles1986** [comment]
This shows we were all likely grossly over-estimating the FPS gains we were seeing on-call 😄

**Comment by mpwelton** [comment]
Hi Lewis,
Many thanks for all that. As you say, it's useful to see the FPS so we can see how much 'artistic' choices affect the performance. I reckon we are good to go now. 
I'll try and get a YouTube video up with some accompanying music in the next few days. It might be useful for Andy to have something to show people how techie *and* arty we are.
All the best,
Mark
    On Tuesday 2 July 2024 at 06:07:49 BST, Lewis Cowles ***@***.***> wrote:   

 


This shows we were all likely grossly over-estimating the FPS gains we were seeing on-call 😄
